PortfelIndexBundle:
    resource: "@PortfelIndexBundle/Resources/config/routing.yml"
    prefix:   /

MyPortfelBundle:
    resource: "@MyPortfelBundle/Resources/config/routing.yml"
    prefix:   /

#AdministratorAdminBundle:
#    resource: "@AdministratorAdminBundle/Resources/config/routing.yml"
#    prefix:   /

PortfelSecurityBundle:
    resource: "@PortfelSecurityBundle/Resources/config/routing.yml"
    prefix:   /
