security:
    acl:
        connection: default
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                post_only: true
                use_referer: false
                always_use_default_target_path: true
            logout:
                path:   /user/logout
                target: /
            http_basic:
                realm: "Secured Area"
                
    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }