security:
    acl:
        connection: default
    encoders:
        Portfel\SecurityBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
#        in_memory:
#            users:
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: tomasz21, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: Portfel\SecurityBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                login_path: /
                check_path: /user/login_check
                post_only: true
                use_referer: false
                always_use_default_target_path: true
                default_target_path: /my
#                remember_me: true
            anonymous:    true   
            logout:
                path:   /user/logout
                target: /
                invalidate_session: true
                
            http_basic:
                realm: "Secured Area"
                
            remember_me:
                key:      "a09aec011a0668194f6ce3a992d8c4b3fa821c32"
                lifetime: 1
                name: portfel
                path: /
                domain: ~ 
                always_remember_me: false
                remember_me_parameter: _remember_me
                secure: true
    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/change, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
