parameters:
#    portfel_index.example.class: Portfel\IndexBundle\Example

services:
#    portfel_index.example:
#        class: %portfel_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
