#portfel:
#    pattern:   /my/{id}/portfel
#    defaults:  { _controller: MyPortfelBundle:Operation:index }

my:
    resource: "@MyPortfelBundle/Controller/MyController.php"
    type:     annotation 
    prefix:  /
    
operation:
    resource: "@MyPortfelBundle/Controller/OperationController.php"
    type:     annotation 
    prefix:  /