admin_user:
    pattern:  /
    defaults: { _controller: "PortfelSecurityBundle:User:index" }

admin_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "PortfelSecurityBundle:User:show" }

admin_user_new:
    pattern:  /new
    defaults: { _controller: "PortfelSecurityBundle:User:new" }

admin_user_create:
    pattern:  /create
    defaults: { _controller: "PortfelSecurityBundle:User:create" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PortfelSecurityBundle:User:edit" }

admin_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "PortfelSecurityBundle:User:update" }
    requirements: { _method: post }

admin_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PortfelSecurityBundle:User:delete" }
    requirements: { _method: post }
