#register:
#    pattern:  /register
#    defaults: { _controller: PortfelSecurityBundle:Register:register }



fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_register:
    pattern:  /user/register
    defaults: { _controller: PortfelSecurityBundle:Register:register }
   
fos_user_change_password:
    pattern:  /user/change
    defaults: { _controller: PortfelSecurityBundle:ChangePassword:changePassword }
    
fos_user_resetting:
    pattern:  /user/request
    defaults: { _controller: PortfelSecurityBundle:Resetting:request}

fos_user_resetting_send_email:
    pattern:  /user/sendEmail
    defaults: { _controller: PortfelSecurityBundle:Resetting:sendEmail}

fos_user_resetting_reset:
    pattern:  /user/reset
    defaults: { _controller: PortfelSecurityBundle:Resetting:reset}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group